name: Generate Docs

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "latest"

            - name: Install Dependencies
              run: npm install

            - name: Build Documentation
              uses: andstor/jsdoc-action@v1
              with:
                  source_dir: ./lib # Replace with your source directory
                  output_dir: ./docs # Output directory
                  config_file: jsdoc.json # Optional, if you have a JSDoc config file
                  template: better-docs # Optional, if you want to use a specific template
                  front_page: README.md # Optional, if you want a custom front page

            - name: Upload Documentation as Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: documentation
                  path: ./docs/

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_DEPLOY_TOKEN }}
                  publish_dir: ./docs/
